Repository pmem/pmdk, pull requests merged in 2020-06, with the labels that each got.

#4755 test: tests for pmem2_map with exec protection flag
  src/test/pmem2_map_prot/Makefile
  src/test/pmem2_map_prot/TESTS.py
  src/test/pmem2_map_prot/pmem2_map_prot.c
  src/test/pmem2_map_prot/pmem2_map_prot.vcxproj
  src/test/pmem2_map_prot/pmem2_map_prot.vcxproj.filters
Labels: libpmem2

#4790 pmem2: implement pmem2_source_from_anon()
  doc/Makefile
  doc/libpmem2/.gitignore
  doc/libpmem2/pmem2_source_from_anon.3.md
  src/common/file_posix.c
  src/include/libpmem2.h
  src/libpmem2/badblocks_ndctl.c
  src/libpmem2/deep_flush_linux.c
  src/libpmem2/map.h
  src/libpmem2/map_posix.c
  src/libpmem2/map_windows.c
  src/libpmem2/persist.c
  src/libpmem2/persist_windows.c
  src/libpmem2/pmem2_utils.h
  src/libpmem2/pmem2_utils_linux.c
  src/libpmem2/pmem2_utils_other.c
  src/libpmem2/region_namespace.h
  src/libpmem2/region_namespace_ndctl.c
  src/libpmem2/region_namespace_ndctl.h
  src/libpmem2/region_namespace_none.c
  src/libpmem2/source.c
  src/libpmem2/source.h
  src/libpmem2/source_posix.c
  src/libpmem2/source_windows.c
  src/libpmem2/usc_ndctl.c
  src/libpmem2/usc_windows.c
  src/test/pmem2_badblock_mocks/TESTS.py
  src/test/pmem2_badblock_mocks/mocks_other.c
  src/test/pmem2_badblock_mocks/mocks_pmem2.c
  src/test/pmem2_badblock_mocks/pmem2_badblock_mocks.c
  src/test/pmem2_deep_flush/pmem2_deep_flush.c
  src/test/pmem2_granularity/pmem2_granularity.c
  src/test/pmem2_integration/TESTS.py
  src/test/pmem2_integration/pmem2_integration.c
  src/test/pmem2_map/pmem2_map.c
  src/test/pmem2_perror/pmem2_perror.c
  src/test/pmem2_source/pmem2_source.c
Labels: libpmem2

#4781 check that errno is set for PMEM2_E_ERRNO
  src/libpmem2/pmem2_utils.h
Labels: libpmem2

#4851 common: fix freebsd CI
  .cirrus.yml
Labels: OS: FreeBSD

#4754 clean away __pycache__ dirs
  src/test/Makefile
Labels: build system
