Repository pmem/pmdk, pull requests merged in 2023-06, with the labels that each got.

#5712 test: skip elapsed time calculation when start_time unavailable
  src/test/RUNTESTS.py
  src/test/unittest/basetest.py
Labels: QA: CI, sprint goal

#5713 common: remove FreeBSD from src
  CODING_STYLE.md
  CONTRIBUTING.md
  README.md
  src/common.inc
  src/common/ctl.c
  src/common/file.c
  src/common/file_posix.c
  src/common/mmap.c
  src/common/mmap.h
  src/common/mmap_posix.c
  src/common/os_deep_linux.c
  src/common/set.c
  src/common/set_badblocks.c
  src/common/uuid_freebsd.c
  src/core/errno_freebsd.h
  src/core/fs.h
  src/core/os.h
  src/core/os_posix.c
  src/core/os_thread.h
  src/core/os_thread_posix.c
  src/core/util_posix.c
  src/freebsd/README
  src/freebsd/include/endian.h
  src/freebsd/include/features.h
  src/freebsd/include/linux/kdev_t.h
  src/freebsd/include/linux/limits.h
  src/freebsd/include/sys/sysmacros.h
  src/libpmemobj/lane.c
  src/libpmemobj/obj.h
  src/libpmemobj/sync.c
  src/libpmempool/pool.c
Labels: sprint goal

#5724 common: remove FreeBSD from CI
  .cirrus.yml
  .gitignore
  README.md
Labels: sprint goal

#5722 common: remove FreeBSD from examples and tests
  src/Makefile
  src/examples/libpmemobj/libart/arttree.c
  src/examples/libpmemobj/libart/arttree_structures.c
  src/examples/libpmemobj/pmemobjfs/pmemobjfs.c
  src/examples/libpmemobj/pminvaders/pminvaders.c
  src/examples/libpmemobj/pminvaders/pminvaders2.c
  src/test/ctl_prefault/ctl_prefault.c
  src/test/ex_libpmem/TEST0
  src/test/freebsd.supp
  src/test/pmem2_badblock/TESTS.py
  src/test/pmem2_badblock_mocks/TESTS.py
  src/test/pmem2_deep_flush/TESTS.py
  src/test/pmem2_future/TESTS.py
  src/test/pmem2_granularity/TESTS.py
  src/test/pmem2_granularity/err10.log.match
  src/test/pmem2_granularity/err5.log.match
  src/test/pmem2_map/TESTS.py
  src/test/pmem2_mover/TESTS.py
  src/test/pmem2_source_size/TESTS.py
  src/test/pmem2_usc/TESTS.py
  src/test/tools/fallocate_detect/fallocate_detect.c
  src/test/tools/pmemspoil/spoil.c
  src/test/unittest/unittest.h
  src/test/unittest/unittest.sh
  src/test/unittest/ut.c
  src/test/unittest/utils.py
  src/test/unittest/valgrind.py
Labels: sprint goal

#5728 common: remove leftover Windows
  doc/libpmem2/pmem2_source_from_handle.3
  src/common/file.c
  utils/check-area.sh
Labels: sprint goal

#5725 doc: remove FreeBSD from documentation
  doc/README
  doc/libpmem/libpmem.7.md
  doc/libpmem2/libpmem2.7.md
  doc/libpmem2/pmem2_source_alignment.3.md
  doc/libpmem2/pmem2_source_size.3.md
  doc/libpmemblk/libpmemblk.7.md
  doc/libpmemlog/libpmemlog.7.md
  doc/libpmemobj/libpmemobj.7.md
  doc/libpmemobj/oid_is_null.3.md
  doc/libpmemobj/pmemobj_mutex_zero.3.md
  doc/libpmempool/libpmempool.7.md
  doc/pmempool/pmempool.1.md
  src/libpmemobj/obj.h
Labels: sprint goal

#5732 common: remove miniasync dependencies, docs and tests
  doc/Makefile
  doc/libpmem2/.gitignore
  doc/libpmem2/pmem2_async.3.md
  doc/libpmem2/pmem2_config_set_vdm.3
  doc/libpmem2/pmem2_memcpy_async.3
  doc/libpmem2/pmem2_memmove_async.3
  doc/libpmem2/pmem2_memset_async.3
  src/Makefile
  src/common.inc
  src/common/Makefile
  src/include/libpmem2.h
  src/include/libpmem2/async.h
  src/libpmem/Makefile
  src/libpmem2/Makefile
  src/libpmem2/config.c
  src/libpmem2/config.h
  src/libpmem2/libpmem2.link.in
  src/libpmem2/map.c
  src/libpmem2/map.h
  src/libpmem2/map_posix.c
  src/libpmem2/mover.c
  src/libpmem2/mover.h
  src/libpmemblk/Makefile
  src/libpmemlog/Makefile
  src/libpmemobj/Makefile
  src/libpmempool/Makefile
  src/test/Makefile
  src/test/Makefile.inc
  src/test/pmem2_future/.gitignore
  src/test/pmem2_future/Makefile
  src/test/pmem2_future/TESTS.py
  src/test/pmem2_future/pmem2_future.c
  src/test/pmem2_map/pmem2_map.c
  src/test/pmem2_mover/.gitignore
  src/test/pmem2_mover/Makefile
  src/test/pmem2_mover/TESTS.py
  src/test/pmem2_mover/pmem2_mover.c
  src/test/scope/out13.log.match
  src/test/unittest/consts.py
  src/tools/Makefile.inc
  utils/check-commit.sh
  utils/check_docs/docs_tests.py
Labels: sprint goal

#5733 common: add CentOS to build system
  .github/workflows/centos.yml
  doc/libpmem2/libpmem2.7.md
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/install-valgrind.sh
Labels: DAOS, sprint goal

#5631 common: provide Ansible files for platforms provisioning
  utils/ansible/README
  utils/ansible/README.md
  utils/ansible/configure-pmem.yml
  utils/ansible/opensuse-setup.yml
  utils/ansible/rockylinux-setup.yml
Labels: sprint goal

#5739 common: add support for --force-enable option in RUNTESTS.sh script
  .github/workflows/pmem_long.yml
  .github/workflows/pmem_valgrind_sh.yml
  src/test/Makefile
  src/test/Makefile.inc
  src/test/README
  src/test/RUNTESTS.sh
  src/test/unittest/unittest.sh
  utils/check_whitespace
  utils/docker/run-build-package.sh
Labels: Priority: 3 medium, QA: CI

#5753 common: add the next release changelog entry stub
  ChangeLog
Labels: sprint goal

#5746 test: cleanup pmempool_check from deprecated tests
  ChangeLog
  src/test/pmempool_check/TEST0
  src/test/pmempool_check/TEST1
  src/test/pmempool_check/TEST13
  src/test/pmempool_check/TEST14
  src/test/pmempool_check/TEST15
  src/test/pmempool_check/TEST16
  src/test/pmempool_check/TEST17
  src/test/pmempool_check/TEST18
  src/test/pmempool_check/TEST19
  src/test/pmempool_check/TEST2
  src/test/pmempool_check/TEST22
  src/test/pmempool_check/TEST23
  src/test/pmempool_check/TEST25
  src/test/pmempool_check/TEST27
  src/test/pmempool_check/TEST3
  src/test/pmempool_check/TEST4
  src/test/pmempool_check/TEST5
  src/test/pmempool_check/TEST6
  src/test/pmempool_check/TEST7
  src/test/pmempool_check/TEST8
  src/test/pmempool_check/out0.log.match
  src/test/pmempool_check/out1.log.match
  src/test/pmempool_check/out13.log.match
  src/test/pmempool_check/out14.log.match
  src/test/pmempool_check/out15.log.match
  src/test/pmempool_check/out16.log.match
  src/test/pmempool_check/out17.log.match
  src/test/pmempool_check/out18.log.match
  src/test/pmempool_check/out19.log.match
  src/test/pmempool_check/out22.log.match
  src/test/pmempool_check/out23.log.match
  src/test/pmempool_check/out25.log.match
  src/test/pmempool_check/out27.log.match
  src/test/pmempool_check/out3.log.match
  src/test/pmempool_check/out4.log.match
  src/test/pmempool_check/out5.log.match
  src/test/pmempool_check/out6.log.match
  src/test/pmempool_check/out7.log.match
  src/test/pmempool_check/out8.log.match
Labels: sprint goal

#5748 test: remove log&blk tests from the libpmempool_rm group
  ChangeLog
  src/test/libpmempool_rm/TEST0
  src/test/libpmempool_rm/out0.log.match
Labels: sprint goal

#5750 test: remove deprecated tests other than (lib)pmempool_*
  ChangeLog
  src/test/ctl_cow/TEST1
  src/test/ctl_cow/TEST2
  src/test/ctl_prefault/TEST1
  src/test/ctl_prefault/TEST2
  src/test/magic/TEST0
  src/test/magic/out0.log.match
Labels: sprint goal

#5749 test: cleanup pmempool_[!check] from deprecated tests
  ChangeLog
  src/test/pmempool_dump/TEST0
  src/test/pmempool_dump/out0.log.match
  src/test/pmempool_info/TEST0
  src/test/pmempool_info/TEST1
  src/test/pmempool_info/TEST16
  src/test/pmempool_info/TEST2
  src/test/pmempool_info/TEST27
  src/test/pmempool_info/TEST3
  src/test/pmempool_info/TEST4
  src/test/pmempool_info/TEST5
  src/test/pmempool_info/TEST6
  src/test/pmempool_info/TEST7
  src/test/pmempool_info/TEST8
  src/test/pmempool_info/TEST9
  src/test/pmempool_info/out0.log.match
  src/test/pmempool_info/out1.log.match
  src/test/pmempool_info/out16.log.match
  src/test/pmempool_info/out2.log.match
  src/test/pmempool_info/out27.log.match
  src/test/pmempool_info/out3.log.match
  src/test/pmempool_info/out4.log.match
  src/test/pmempool_info/out5.log.match
  src/test/pmempool_info/out6.log.match
  src/test/pmempool_info/out7.log.match
  src/test/pmempool_info/out8.log.match
  src/test/pmempool_info/out9.log.match
  src/test/pmempool_inval/TEST0
  src/test/pmempool_inval/out0.log.match
  src/test/pmempool_rm/TEST0
  src/test/pmempool_rm/TEST1
  src/test/pmempool_rm/TEST10
  src/test/pmempool_rm/TEST11
  src/test/pmempool_rm/out0.log.match
  src/test/pmempool_rm/out1.log.match
  src/test/pmempool_sync/TEST26
  src/test/pmempool_sync/out26.log.match
Labels: sprint goal

#5756 test: adjust tests to not use libpmemblk
  ChangeLog
  src/test/compat_incompat_features/Makefile
  src/test/compat_incompat_features/TEST0
  src/test/compat_incompat_features/TEST1
  src/test/compat_incompat_features/TEST2
  src/test/compat_incompat_features/TEST3
  src/test/compat_incompat_features/TEST4
  src/test/compat_incompat_features/common.sh
  src/test/compat_incompat_features/err1.log.match
  src/test/compat_incompat_features/err2.log.match
  src/test/compat_incompat_features/err3.log.match
  src/test/compat_incompat_features/err4.log.match
  src/test/compat_incompat_features/out0.log.match
  src/test/compat_incompat_features/out1.log.match
  src/test/compat_incompat_features/out2.log.match
  src/test/compat_incompat_features/out3.log.match
  src/test/compat_incompat_features/out4.log.match
  src/test/compat_incompat_features/pool_open.c
  src/test/ctl_cow/Makefile
  src/test/ctl_cow/ctl_cow.c
  src/test/ctl_prefault/Makefile
  src/test/ctl_prefault/TEST0
  src/test/ctl_prefault/ctl_prefault.c
  src/test/out_err_mt/Makefile
  src/test/out_err_mt/TEST0
  src/test/out_err_mt/TEST1
  src/test/out_err_mt/TEST2
  src/test/out_err_mt/out0.log.match
  src/test/out_err_mt/out1.log.match
  src/test/out_err_mt/out2.log.match
  src/test/out_err_mt/out_err_mt.c
  src/test/pmempool_check/TEST20
  src/test/pmempool_check/out20.log.match
  src/test/pmempool_create/TEST0
  src/test/pmempool_create/TEST2
  src/test/pmempool_create/TEST3
  src/test/pmempool_create/TEST4
  src/test/pmempool_create/TEST5
  src/test/pmempool_create/TEST6
  src/test/pmempool_create/TEST8
  src/test/pmempool_create/err5.log.match
  src/test/set_funcs/Makefile
  src/test/set_funcs/set_funcs.c
  src/test/traces_pmem/Makefile
  src/test/traces_pmem/TEST0
  src/test/traces_pmem/trace_pmemblk_head0.log.match
  src/test/traces_pmem/traces_pmem.c
Labels: sprint goal

#5758 common: disable pmem check tests for every pull request
  .github/workflows/pmem_check.yml
Labels: sprint goal

#5742 common: a playbook for GHA self-hosted runner configuration
  utils/ansible/README.md
  utils/ansible/ansible.cfg
  utils/ansible/configure-self-hosted-runner.yml
Labels: Priority: 3 medium, QA: CI

#5761 common: disable pmem ras test for every pull request
  .github/workflows/pmem_ras.yml
Labels: build system, sprint goal

#5740 common: Unified pmem tests
  .github/workflows/pmem_check.yml
  .github/workflows/pmem_long.yml
  .github/workflows/pmem_valgrind.yml
  .github/workflows/pmem_valgrind_py.yml
  doc/pmempool/pmempool.1.md
  src/test/.gitignore
  src/test/Makefile.inc
  src/test/README
  src/test/RUNTESTS.sh
  src/test/ex_libpmem2/TESTS.py
  src/test/obj_debug/TEST0
  src/test/obj_debug/TEST1
  src/test/obj_debug/TEST2
  src/test/obj_debug/TEST3
  src/test/obj_debug/TEST4
  src/test/obj_debug/TEST5
  src/test/obj_fragmentation2/TESTS.py
  src/test/obj_ulog_size/TESTS.py
  src/test/pmem_movnt_align/TEST0
  src/test/pmem_movnt_align/TEST2
  src/test/scope/TESTS.py
  src/test/testconfig.py.example
  src/test/testconfig.sh.example
  src/test/tools/anonymous_mmap/Makefile
  src/test/tools/anonymous_mmap/check_max_mmap.sh
  src/test/traces_pmem/TEST0
  src/test/unittest/builds.py
  src/test/unittest/consts.py
  src/test/unittest/futils.py
  src/test/unittest/unittest.sh
  src/tools/.gitignore
  src/tools/Makefile.inc
  utils/docker/configure-tests.sh
Labels: Priority: 3 medium, QA: CI
