Repository pmem/pmdk, pull requests merged in 2023-08, with the labels that each got.

#5837 common: prepare changelog for the upcoming release
  ChangeLog
Labels: sprint goal

#5840 common: why Python-based tests are not used for package testing
  utils/docker/run-build-package.sh
Labels: sprint goal

#5841 common: view the Coverity log file
  utils/docker/run-coverity.sh
Labels: sprint goal

#5855 test: fix granularity requirement check
  src/test/unittest/granularity.py
Labels: sprint goal

#5856 test: add a comment on the effect of device DAXes order
  src/test/unittest/unittest.sh
Labels: sprint goal

#5835 common: force changelog update on PR
  .github/workflows/main.yml
Labels: no changelog

#5857 test: add comment about req_tty to ex_libpmemobj tests
  src/test/ex_libpmemobj/TEST15
  src/test/ex_libpmemobj/TEST16
Labels: sprint goal, no changelog

#5858 common: fix granularity requirement check (changelog entry)
  ChangeLog
Labels: sprint goal

#5860 common: 2.0.0 release
  ChangeLog
  INSTALL.md
Labels: sprint goal

#5861 common: 2.0.0 release
  ChangeLog
  INSTALL.md
Labels: sprint goal

#5811 test: 'none' value of force-enable to optimize PMem workflow
  .github/workflows/pmem_valgrind.yml
  src/test/README
  src/test/RUNTESTS.sh
  src/test/unittest/configurator.py
  src/test/unittest/unittest.sh
Labels: QA: CI, no changelog

#5866 pool: fix coverity issue 374612
  src/tools/pmempool/common.c
Labels: pmempool, no changelog

#5867 test: force-enable to accept none value (fix)
  src/test/unittest/valgrind.py
Labels: sprint goal, no changelog

#5868 test: fix CHECK_TYPE behaviour
  src/test/RUNTESTS.sh
  src/test/unittest/unittest.sh
Labels: sprint goal, no changelog

#5871 test: disable pmem2_integration/33-37 under pmemcheck
  src/test/pmem2_integration/TESTS.py
Labels: sprint goal, no changelog

#5862 common: update PMDK version
  RELEASE_STEPS.md
  utils/docker/images/set-images-version.sh
Labels: sprint goal, no changelog

#5869 common: simplify pmem_test_procedure for Python-based tests
  .github/actions/pmem_test_procedure/action.yml
Labels: sprint goal, no changelog

#5874 doc: fix links to PMDK tutorials
  README.md
Labels: sprint goal, no changelog

#5877 doc: rename 1.14.0 to 2.0.0
  ChangeLog
  RELEASE_STEPS.md
Labels: sprint goal

#5873 common: integrate all PMem workflows
  .github/actions/pmem_test_prepare/action.yml
  .github/actions/pmem_test_procedure/action.yml
  .github/actions/pmem_test_run/action.yml
  .github/workflows/pmem_check.yml
  .github/workflows/pmem_long.yml
  .github/workflows/pmem_test_matrix.yml
  .github/workflows/pmem_tests.yml
  .github/workflows/pmem_tests_main.yml
  .github/workflows/pmem_valgrind.yml
  src/test/unittest/test_types.py
Labels: sprint goal, no changelog

#5878 doc: rename 1.14.0 to 2.0.0
  ChangeLog
  RELEASE_STEPS.md
Labels: sprint goal, no changelog
