Repository pmem/pmdk, pull requests merged in 2023-05, with the labels that each got.

#5677 test: display execution time of each test
  utils/gha-runners/create-testconfig.sh
Labels: QA: CI

#5679 test: fix pmem2_mover/TEST1 with memcheck for #5678
  src/test/pmem2_mover/pmem2_mover.c
Labels: QA: CI

#5680 test: add missing persist in obj_tx_alloc_mt/TEST1
  src/test/obj_tx_alloc_mt/obj_tx_alloc_mt.c
Labels: QA: CI

#5685 common: enable manula trigerring of long tests
  .github/workflows/unittest_long.yml
Labels: QA: CI

#5683 common: Increasing the parallelism of test execution
  .github/workflows/unittest.yml
  .github/workflows/unittest_long.yml
  .github/workflows/unittest_valgrind_py.yml
  .github/workflows/unittest_valgrind_sh.yml
  utils/gha-runners/build-pmdk.sh
Labels: QA: CI

#5684 common: print elapsed time for failed tests
  src/test/RUNTESTS.py
  src/test/unittest/basetest.py
Labels: QA: CI

#5688 test: disable pmem2_mover/TEST[6-8] (pmemcheck/byte)
  src/test/pmem2_mover/TESTS.py
Labels: libpmem2, QA: CI, miniasync

#5689 test: disable pmem2_vm_reservation/TEST22 w/ Valgrind
  src/test/pmem2_vm_reservation/TESTS.py
Labels: libpmem2, QA: CI

#5704 test: disable obj_sync/TEST[2,5-6] for all configurations until #5646 is fixed
  src/test/obj_sync/DISABLE_TEST2
  src/test/obj_sync/DISABLE_TEST5
  src/test/obj_sync/DISABLE_TEST6
Labels: sprint goal

#5709 common: 1.13.1 release
  ChangeLog
  README.md
Labels: sprint goal
