Repository pmem/pmdk, pull requests merged in 2023-10, with the labels that each got.

#5885 FEAT: permanent mounting of PMem in ansible script
  utils/ansible/configure-pmem.yml
Labels: no changelog

#5890 common: fix libpmem CFLAGS
  ChangeLog
  src/Makefile.inc
  src/libpmem/Makefile
Labels: DAOS, sprint goal

#5887 Stack usage generation enabling.
  src/Makefile.inc
  src/stats/stack-usage-debug.txt
  src/stats/stack-usage-nondebug.txt
  utils/stack-usage-stats.sh
Labels: libpmemobj, DAOS, sprint goal, no changelog
