Repository pmem/pmdk, pull requests merged in 2023-11, with the labels that each got.

#5898 common: stack usage in one file
  src/stats/stack-usage-debug.txt
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/stack_usage_nondebug.txt
  utils/call_stacks_analysis/stack_usage_stats.sh
Labels: DAOS, sprint goal, no changelog

#5899 common: generate public API list based on linker file
  utils/call_stacks_analysis/api-from-link-file.sh
Labels: DAOS, sprint goal, no changelog

#5903 common: call stack analysis - usability fixes
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/api-from-link-file.sh
  utils/call_stacks_analysis/generate_call_stacks.py
  utils/call_stacks_analysis/make_api.sh
  utils/call_stacks_analysis/make_stack_usage.sh
  utils/call_stacks_analysis/stack_usage.txt
  utils/call_stacks_analysis/stack_usage_stats.sh
Labels: sprint goal, no changelog

#5902 common: drop config in call_stacks_analysis
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/examples/config.json
  utils/call_stacks_analysis/generate_call_stacks.py
  utils/call_stacks_analysis/libpmem/config.json
  utils/call_stacks_analysis/libpmem/make_config.py
  utils/call_stacks_analysis/libpmem/white_list.json
  utils/call_stacks_analysis/libpmemobj/config.json
  utils/call_stacks_analysis/libpmemobj/white_list.json
  utils/call_stacks_analysis/make_extra_calls.py
Labels: sprint goal, no changelog

#5900 cflow.sh with api.txt as input parameter
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/make_cflow.sh
Labels: DAOS, sprint goal, no changelog

#5901 common: add sample api_filter file
  utils/call_stacks_analysis/examples/api_filter.txt
Labels: DAOS, sprint goal, no changelog

#5905 common: loading the api from file + small fixes
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/generate_call_stacks.py
Labels: sprint goal, no changelog

#5906 common: add api_filter parameter + small fix
  utils/call_stacks_analysis/generate_call_stacks.py
Labels: DAOS, sprint goal, no changelog

#5911 common: work around cflow's for-loop issue
  utils/call_stacks_analysis/make_cflow.sh
Labels: sprint goal, no changelog

#5907 common: pass the validation step
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/generate_call_stacks.py
  utils/call_stacks_analysis/make_api.sh
  utils/call_stacks_analysis/make_cflow.sh
  utils/call_stacks_analysis/make_extra.py
  utils/call_stacks_analysis/white_list.json
Labels: sprint goal, no changelog

#5909 common: introduce the lower limit parameter
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/generate_call_stacks.py
Labels: sprint goal, no changelog

#5910 common: revisit accessory scripts
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/list_api_callers.py
  utils/call_stacks_analysis/list_stack_usage.py
Labels: sprint goal, no changelog

#5913 common: use relative path for stack usage files
  utils/call_stacks_analysis/make_stack_usage.sh
Labels: DAOS, sprint goal, no changelog

#5912 common: assume const size of ndctl stack consumption
  utils/call_stacks_analysis/generate_call_stacks.py
Labels: DAOS, sprint goal, no changelog

#5914 common: revert automatically all changes made for cflow analysis
  utils/call_stacks_analysis/make_cflow.sh
Labels: sprint goal, no changelog

#5915 common: generate_call_stacks.py -> make_call_stacks.py
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5893 obj: reduce stack usage of obj_vg_check_no_undef
  ChangeLog
  src/libpmemobj/obj.c
  utils/call_stacks_analysis/stack_usage.txt
Labels: libpmemobj, DAOS, sprint goal

#5916 common: generate_call_stacks.py -> make_call_stacks.py (fix)
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5917 common: raise an exception instead of assert() call
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5919 common: go through API calls with the call stacks generation
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5920 common: add more stack usage examples to support existing regex
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5921 common: reduce the actual number of stack to analyze
  utils/call_stacks_analysis/make_call_stacks.py
Labels: DAOS, sprint goal, no changelog

#5923 common: add const stack usage for all daxctl* functions
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5922 common: skip by default dumping call_stacks_all.json file
  utils/call_stacks_analysis/make_call_stacks.py
Labels: DAOS, sprint goal, no changelog

#5924 common: check zero-sized functions
  utils/call_stacks_analysis/README.md
  utils/call_stacks_analysis/check_stack_usage.sh
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5925 pmem2: reduce stack usage of pmem2_get_type_from_stat
  src/libpmem2/pmem2_utils_linux.c
Labels: sprint goal, no changelog

#5926 common: final ndctl/daxctl stack usage with recurrence
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5927 pmem2: reduce stack usage of pmem2_get_type_from_stat (fix)
  utils/call_stacks_analysis/stack_usage.txt
Labels: sprint goal, no changelog

#5929 pmem: remove unused code of membuf
  src/core/membuf.c
  src/core/membuf.h
  src/core/pmemcore.inc
  src/test/Makefile.inc
Labels: sprint goal, no changelog

#5928 common: fix call stack analysis .gitignore
  utils/call_stacks_analysis/.gitignore
Labels: sprint goal, no changelog

#5933 obj: fix coverity issue heap_get_arena_auto
  src/libpmemobj/heap.c
Labels: sprint goal, no changelog

#5931 common: extend example run sequence
  utils/call_stacks_analysis/README.md
Labels: sprint goal, no changelog

#5937 common: introduce a stack usage scan
  .github/workflows/scan_stack_usage.yml
  .github/workflows/scans.yml
Labels: sprint goal, no changelog

#5932 common: remove obsolete dependency: cmake
  .github/workflows/scan_codeql.yml
  .github/workflows/scan_documentation.yml
  utils/ansible/opensuse-setup.yml
  utils/ansible/rockylinux-setup.yml
  utils/check_license/check-headers.sh
  utils/check_whitespace
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.fedora-37
  utils/docker/images/Dockerfile.opensuse-leap-15
  utils/docker/images/Dockerfile.rockylinux-8
  utils/docker/images/Dockerfile.rockylinux-9
  utils/docker/images/Dockerfile.ubuntu-22.04
  utils/gha-runners/run-ras-linux.yml
Labels: obsolete-src, no changelog

#5938 common: adjust the stack usage size limit to account for small differences between OSes
  .github/workflows/scan_stack_usage.yml
Labels: sprint goal, no changelog

#5939 common: remove assert from make_call_stacks.py
  utils/call_stacks_analysis/make_call_stacks.py
Labels: sprint goal, no changelog

#5940 common: enable coverity scan on workflow_dispatch event
  utils/docker/run-coverity.sh
Labels: no changelog

#5942 common: remove stack_usage.txt from repo
  .github/workflows/scan_stack_usage.yml
  utils/call_stacks_analysis/.gitignore
  utils/call_stacks_analysis/stack_usage.txt
Labels: sprint goal, no changelog

#5908 common: Add kernel and os packages update playbook
  utils/ansible/README.md
  utils/ansible/handlers/reboot.yml
  utils/ansible/roles/update_rocky/tasks/main.yml
  utils/ansible/roles/update_suse/tasks/main.yml
  utils/ansible/update-os.yml
Labels: sprint goal, no changelog

#5918 common: Add composite action for update-os playbook
  .github/actions/pmem_host_update/action.yml
Labels: sprint goal, no changelog

#5930 common: Integrate update-os into PMEM test prepare
  .github/actions/pmem_test_prepare/action.yml
Labels: sprint goal, no changelog

#5949 common: Add fix for DAX permissions reset after platform reboot
  .github/actions/pmem_test_prepare/action.yml
  .github/actions/update_dax_permissions/action.yml
Labels: no changelog

#5945 Release 2.0.1 rc1
  ChangeLog
Labels: sprint goal
