Repository pmem/pmdk, pull requests merged in 2023-07, with the labels that each got.

#5763 test: remove libpmemobj examples using blk/log
  src/examples/libpmemobj/Makefile
  src/examples/libpmemobj/pmemblk/.gitignore
  src/examples/libpmemobj/pmemblk/Makefile
  src/examples/libpmemobj/pmemblk/README
  src/examples/libpmemobj/pmemblk/obj_pmemblk.c
  src/examples/libpmemobj/pmemlog/.gitignore
  src/examples/libpmemobj/pmemlog/Makefile
  src/examples/libpmemobj/pmemlog/README
  src/examples/libpmemobj/pmemlog/obj_pmemlog.c
  src/examples/libpmemobj/pmemlog/obj_pmemlog_macros.c
  src/examples/libpmemobj/pmemlog/obj_pmemlog_minimal.c
  src/examples/libpmemobj/pmemlog/obj_pmemlog_simple.c
  src/test/ex_libpmemobj/Makefile
  src/test/ex_libpmemobj/TEST10
  src/test/ex_libpmemobj/TEST11
  src/test/ex_libpmemobj/TEST12
  src/test/ex_libpmemobj/TEST13
  src/test/ex_libpmemobj/TEST14
  src/test/ex_libpmemobj/err10.log.match
  src/test/ex_libpmemobj/out10.log.match
  src/test/ex_libpmemobj/out11.log.match
  src/test/ex_libpmemobj/out12.log.match
  src/test/ex_libpmemobj/out13.log.match
  src/test/ex_libpmemobj/out14.log.match
Labels: sprint goal

#5769 common: remove log from benchmarks
  src/benchmarks/Makefile
  src/benchmarks/log.cpp
  src/benchmarks/perf.cfg
  src/benchmarks/pmembench_log.cfg
Labels: libpmemlog, pmembench, sprint goal

#5759 common: pmempool documentation w/o btt/log/blk
  doc/pmempool/pmempool-check.1.md
  doc/pmempool/pmempool-convert.1.md
  doc/pmempool/pmempool-create.1.md
  doc/pmempool/pmempool-dump.1.md
  doc/pmempool/pmempool-feature.1.md
  doc/pmempool/pmempool-info.1.md
  doc/pmempool/pmempool-rm.1.md
  doc/pmempool/pmempool-sync.1.md
  doc/pmempool/pmempool-transform.1.md
  doc/pmempool/pmempool.1.md
  src/tools/pmempool/README
Labels: sprint goal

#5760 test: remove libpmemlog tests
  src/test/Makefile.inc
  src/test/libpmempool_backup/TEST0
  src/test/libpmempool_backup/TEST1
  src/test/libpmempool_backup/TEST2
  src/test/libpmempool_backup/TEST3
  src/test/libpmempool_backup/TEST4
  src/test/libpmempool_backup/TEST5
  src/test/libpmempool_backup/TEST6
  src/test/libpmempool_backup/TEST7
  src/test/libpmempool_backup/common.sh
  src/test/unittest/consts.py
  src/test/unittest/unittest.sh
Labels: sprint goal

#5770 common: remove libpmemblk documentation
  ChangeLog
  README.md
  doc/Makefile
  doc/README
  doc/libpmem/libpmem.7.md
  doc/libpmem2/libpmem2.7.md
  doc/libpmemblk/.gitignore
  doc/libpmemblk/libpmemblk.7.md
  doc/libpmemblk/pmemblk_bsize.3.md
  doc/libpmemblk/pmemblk_check.3
  doc/libpmemblk/pmemblk_check_version.3
  doc/libpmemblk/pmemblk_close.3
  doc/libpmemblk/pmemblk_create.3.md
  doc/libpmemblk/pmemblk_ctl_exec.3
  doc/libpmemblk/pmemblk_ctl_get.3.md
  doc/libpmemblk/pmemblk_ctl_set.3
  doc/libpmemblk/pmemblk_errormsg.3
  doc/libpmemblk/pmemblk_nblock.3
  doc/libpmemblk/pmemblk_open.3
  doc/libpmemblk/pmemblk_read.3.md
  doc/libpmemblk/pmemblk_set_error.3
  doc/libpmemblk/pmemblk_set_funcs.3
  doc/libpmemblk/pmemblk_set_zero.3.md
  doc/libpmemblk/pmemblk_write.3
  doc/libpmemlog/libpmemlog.7.md
  doc/libpmemobj/libpmemobj.7.md
  doc/libpmempool/libpmempool.7.md
  doc/libpmempool/pmempool_check_init.3.md
  doc/libpmempool/pmempool_sync.3.md
  doc/pmem_ctl/pmem_ctl.5.md
  doc/pmempool/pmempool-check.1.md
  doc/poolset/poolset.5.md
  utils/check-area.sh
  utils/check_docs/docs_tests.py
  utils/get_aliases.sh
Labels: libpmemblk, documentation, sprint goal

#5774 doc: remove log and blk references from libpmempool
  doc/libpmempool/libpmempool.7.md
  doc/libpmempool/pmempool_check_init.3.md
  doc/libpmempool/pmempool_rm.3.md
  doc/libpmempool/pmempool_sync.3.md
Labels: sprint goal

#5773 common: remove log src
  CODING_STYLE.md
  ChangeLog
  README.md
  src/Makefile
  src/Makefile.inc
  src/examples/Examples.sln
  src/examples/README
  src/include/README
  src/include/libpmemlog.h
  src/libpmemlog/Makefile
  src/libpmemlog/libpmemlog.c
  src/libpmemlog/libpmemlog.link.in
  src/libpmemlog/log.c
  src/libpmemlog/log.h
  src/tools/Makefile.inc
  utils/build-dpkg.sh
  utils/check-area.sh
  utils/check-commit.sh
  utils/check_docs/docs_tests.py
  utils/docker/arm64.blacklist
  utils/get_aliases.sh
  utils/libpmemlog.pc.in
  utils/pmdk.spec.in
Labels: sprint goal

#5776 common: separate workflow for rebuilding Docker images
  .github/workflows/centos.yml
  .github/workflows/docker_rebuild.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
Labels: sprint goal

#5777 common: introduce preliminary checks GHA
  .github/workflows/centos.yml
  .github/workflows/main.yml
  .github/workflows/ubuntu.yml
Labels: sprint goal

#5778 common: stop the failing Codecov uploader from stopping the build
  .github/workflows/ubuntu.yml
Labels: sprint goal

#5775 doc: remove libpmemlog
  ChangeLog
  doc/Makefile
  doc/README
  doc/libpmem/libpmem.7.md
  doc/libpmem2/libpmem2.7.md
  doc/libpmemlog/.gitignore
  doc/libpmemlog/libpmemlog.7.md
  doc/libpmemlog/pmemlog_append.3.md
  doc/libpmemlog/pmemlog_appendv.3
  doc/libpmemlog/pmemlog_check.3
  doc/libpmemlog/pmemlog_check_version.3
  doc/libpmemlog/pmemlog_close.3
  doc/libpmemlog/pmemlog_create.3.md
  doc/libpmemlog/pmemlog_ctl_exec.3
  doc/libpmemlog/pmemlog_ctl_get.3.md
  doc/libpmemlog/pmemlog_ctl_set.3
  doc/libpmemlog/pmemlog_errormsg.3
  doc/libpmemlog/pmemlog_nbyte.3.md
  doc/libpmemlog/pmemlog_open.3
  doc/libpmemlog/pmemlog_rewind.3
  doc/libpmemlog/pmemlog_set_funcs.3
  doc/libpmemlog/pmemlog_tell.3.md
  doc/libpmemlog/pmemlog_walk.3
  doc/libpmemobj/libpmemobj.7.md
  doc/pmem_ctl/pmem_ctl.5.md
  doc/poolset/poolset.5.md
Labels: sprint goal

#5779 common: remove libpmemblk source code
  CODING_STYLE.md
  ChangeLog
  src/Makefile
  src/Makefile.inc
  src/include/README
  src/include/libpmemblk.h
  src/include/libpmempool.h
  src/libpmemblk/Makefile
  src/libpmemblk/blk.c
  src/libpmemblk/blk.h
  src/libpmemblk/btt.c
  src/libpmemblk/btt.h
  src/libpmemblk/btt_layout.h
  src/libpmemblk/libpmemblk.c
  src/libpmemblk/libpmemblk.link.in
  src/libpmemlog/log.c
  src/test/tools/ddmap/Makefile
  src/test/tools/pmemobjcli/Makefile
  src/tools/Makefile.inc
  src/tools/pmempool/dump.c
  utils/build-dpkg.sh
  utils/check-commit.sh
  utils/docker/arm64.blacklist
  utils/libpmemblk.pc.in
  utils/pmdk.spec.in
Labels: libpmemblk, sprint goal

#5783 common: remove blk/log - second iteration
  ChangeLog
  src/Makefile
  src/libpmemlog/log.c
  src/test/unittest/unittest.sh
  utils/pmdk.magic
Labels: sprint goal

#5785 test: delete logging into stdout
  src/test/pmempool_check/TEST8
Labels: sprint goal

#5789 Use dedicated DISABLED() function to disable tests in bash test framework
  src/test/obj_sync/TEST2
  src/test/obj_sync/TEST5
  src/test/obj_sync/TEST6
  src/test/unittest/unittest.sh
Labels: QA: CI, sprint goal

#5798 common: restore the env.py ansible library
  utils/ansible/library/env.py
Labels: QA: CI, sprint goal

#5794 common: pass secret variables to scan_coverity.yml reusing workflow
  .github/workflows/scan_coverity.yml
  .github/workflows/scans.yml
Labels: QA: CI, sprint goal

#5792 Use dedicated DISABLED() function to disable tests in Python test framework
  src/test/RUNTESTS.py
  src/test/pmem2_badblock/TESTS.py
  src/test/unittest/basetest.py
  src/test/unittest/futils.py
  src/test/unittest/utils.py
Labels: QA: CI, sprint goal

#5782 common: cleanup README
  README.md
Labels: documentation

#5795 test: disable obj_sync/TEST4 until #5699 and #5706 are fixed.
  src/test/obj_sync/TEST4
Labels: QA: CI, sprint goal

#5796 test: disable pmempool_sync/TEST18 until #5708 is fixed
  src/test/pmempool_sync/TEST18
Labels: QA: CI, sprint goal

#5797 test: print error/warning message in case of Valgrind failure
  src/test/unittest/python_gdb.py
Labels: QA: CI, libpmemobj, sprint goal

#5799 test: avoid unnecessary skip in case of different expected test type
  src/test/libpmempool_backup/TEST6
  src/test/obj_many_size_allocs/TEST0
  src/test/obj_pmalloc_mt/TEST0
  src/test/obj_pmalloc_mt/TEST2
  src/test/obj_pmalloc_mt/TEST3
  src/test/obj_pmalloc_rand_mt/TEST0
  src/test/obj_reserve_mt/TEST0
  src/test/obj_reserve_mt/TEST2
  src/test/obj_reserve_mt/TEST3
  src/test/obj_tx_alloc_mt/TEST0
  src/test/obj_tx_alloc_mt/TEST2
  src/test/obj_tx_flow/TEST0
  src/test/obj_tx_locks/TEST0
  src/test/obj_zones/TEST0
  src/test/obj_zones/TEST1
Labels: QA: CI, sprint goal

#5800 pool: remove unreachable code
  src/tools/pmempool/dump.c
Labels: sprint goal

#5803 common: unify testconfig generation scripts
  .github/workflows/pmem_check.yml
  .github/workflows/pmem_long.yml
  .github/workflows/pmem_valgrind.yml
  utils/create-testconfig.sh
  utils/docker/configure-tests.sh
  utils/docker/prepare-for-build.sh
  utils/docker/run-build-package.sh
  utils/gha-runners/create-testconfig.sh
Labels: build system, sprint goal

#5804 common: force rebuild docker images
  .github/workflows/docker_rebuild.yml
  utils/docker/pull-or-rebuild-image.sh
Labels: build system, sprint goal

#5786 common: separate make commands for whitespace and commits checking
  ChangeLog
  Makefile
Labels: QA: CI

#5807 common: introduce simple PR testing approach
  .github/workflows/centos.yml
  .github/workflows/main.yml
  .github/workflows/ubuntu.yml
Labels: build system, sprint goal

#5808 test: disable failing tests
  src/test/obj_pmalloc_mt/TEST1
  src/test/obj_sync/TEST0
  src/test/obj_sync/TEST1
  src/test/obj_sync/TEST2
  src/test/obj_sync/TEST3
  src/test/obj_sync/TEST5
  src/test/obj_sync/TEST6
  src/test/obj_sync/TEST7
  src/test/pmem2_vm_reservation/TESTS.py
Labels: sprint goal

#5810 common: fix licenses for #5759
  src/test/obj_sync/TEST4
  src/test/pmempool_sync/TEST18
  src/test/unittest/python_gdb.py
  utils/md2man.sh
Labels: sprint goal

#5806 common: add coverage scan
  .github/workflows/scan_coverage.yml
  .github/workflows/scans.yml
  .github/workflows/ubuntu.yml
Labels: build system, sprint goal

#5809 common: fix ndctl & jq detection for testconfig generation
  utils/create-testconfig.sh
Labels: build system, sprint goal

#5812 common: longer history is required for make check-license
  .github/workflows/main.yml
Labels: sprint goal

#5817 test: add a test that checks performance without valgrind
  src/test/obj_sync/TEST0
  src/test/obj_sync/err0.log.match
  src/test/obj_sync/out0.log.match
Labels: sprint goal

#5815 common: drop Debian and Fedora from CI
  .github/workflows/docker_rebuild.yml
  .github/workflows/nightly.yml
Labels: sprint goal

#5818 common: simplified pmem.io doc update
  .github/workflows/pmem.io_doc_update.yml
  utils/docker/build-CI.sh
  utils/docker/run-build.sh
  utils/run-doc-update.sh
Labels: sprint goal

#5820 test: improve err_log.match file
  src/test/obj_sync/err0.log.match
Labels: sprint goal

#5819 common: add UBSAN build
  .github/workflows/scan_ubsan.yml
  .github/workflows/scans.yml
Labels: sprint goal

#5821 test: introduce fault_injection test label
  src/test/RUNTESTS.py
  src/test/obj_bucket/TEST0
  src/test/obj_critnib/TESTS.py
  src/test/obj_heap/TEST1
  src/test/obj_lane/TEST0
  src/test/obj_pool/TEST20
  src/test/obj_tx_flow/TEST0
  src/test/obj_tx_lock/TEST0
  src/test/pmem2_config/TESTS.py
  src/test/pmem2_map_from_existing/TESTS.py
  src/test/pmem2_source/TESTS.py
  src/test/pmem2_vm_reservation/TESTS.py
  src/test/pmem_is_pmem_posix/TEST0
  src/test/pmem_is_pmem_posix/TEST4
  src/test/pmem_is_pmem_posix/TEST5
  src/test/scope/TESTS.py
  src/test/unittest/basetest.py
  src/test/unittest/configurator.py
  src/test/unittest/unittest.sh
  src/test/util_badblock/TEST11
  src/test/util_ctl/TEST0
  src/test/util_ctl/TEST1
  src/test/util_poolset/TEST4
  src/test/util_poolset_parse/TEST5
  src/test/util_ravl/TEST0
Labels: sprint goal

#5823 common: rationalize fault injection testing
  .github/workflows/nightly.yml
  .github/workflows/pmem_check.yml
Labels: sprint goal

#5824 common: (fix) move PKG-specific variables out of the testconfig...
  utils/docker/run-build-package.sh
Labels: sprint goal

#5822 common: update RELEASE_STEPS.md file
  RELEASE_STEPS.md
Labels: sprint goal

#5828 common: introduce action/pmem_test_procedure
  .github/actions/pmem_test_procedure/action.yml
  .github/workflows/pmem_check.yml
Labels: sprint goal

#5830 common: add coverage build
  .github/workflows/main.yml
  .github/workflows/ubuntu.yml
Labels: sprint goal

#5831 common: drop EXPERIMENTAL builds testing
  .github/workflows/nightly.yml
Labels: sprint goal

#5832 common: split nightly into in-tree and packaging testing
  .github/workflows/nightly.yml
Labels: sprint goal

#5834 common: no fail-fast and no Docker rebuild on nightly
  .github/workflows/nightly.yml
Labels: sprint goal

#5833 common: split README.md file to README.md and INSTALL.md files
  INSTALL.md
  README.md
  RELEASE_STEPS.md
Labels: sprint goal

#5826 common: update README.md file
  README.md
Labels: sprint goal
