Repository pmem/pmdk, pull requests merged in 2024-03, with the labels that each got.

#6029 common: core_log_default_function() ut
  src/core/log_default.c
  src/test/Makefile
  src/test/core_log_default_function/.gitignore
  src/test/core_log_default_function/Makefile
  src/test/core_log_default_function/TESTS.py
  src/test/core_log_default_function/core_log_default_function.c
  src/test/core_log_internal/Makefile
  src/test/unittest/unittest.h
Labels: sprint goal, no changelog

#6035 common: core_log_set/get_threshold MT unit tests
  src/core/log.c
  src/test/Makefile
  src/test/core_log_mt/.gitignore
  src/test/core_log_mt/Makefile
  src/test/core_log_mt/TESTS.py
  src/test/core_log_mt/core_log_mt.c
Labels: sprint goal, no changelog

#6033 test: introduce core_log() unit tests
  src/core/log_internal.h
  src/test/Makefile
  src/test/core_log/.gitignore
  src/test/core_log/Makefile
  src/test/core_log/Makefile.inc
  src/test/core_log/TESTS.py
  src/test/core_log/core_log.c
  src/test/core_log/core_log_common.c
  src/test/core_log/core_log_common.h
  src/test/core_log_internal/core_log_internal.c
  src/test/core_log_no_func/.gitignore
  src/test/core_log_no_func/Makefile
  src/test/core_log_no_func/TESTS.py
  src/test/core_log_no_func/core_log_no_func.c
  src/test/unittest/unittest.h
Labels: sprint goal, no changelog

#6037 common: drop the logging context
  src/core/log.c
  src/core/log_default.c
  src/core/log_default.h
  src/core/log_internal.h
  src/core/out.c
  src/include/libpmemobj/log.h
  src/libpmemobj/obj_log.c
  src/test/core_log/core_log.c
  src/test/core_log/core_log_common.c
  src/test/core_log_default_function/core_log_default_function.c
  src/test/core_log_internal/core_log_internal.c
  src/test/unittest/unittest.h
  src/test/unittest/ut_log.c
Labels: sprint goal, no changelog

#6038 common: core_log_set/get_threshold MT unit tests (part 2)
  src/core/log.c
  src/core/log_default.c
  src/core/log_internal.h
  src/test/Makefile
  src/test/core_log_mt/.gitignore
  src/test/core_log_mt/core_log_mt.c
  src/test/core_log_threshold_mt/.gitignore
  src/test/core_log_threshold_mt/Makefile
  src/test/core_log_threshold_mt/TESTS.py
  src/test/core_log_threshold_mt/core_log_threshold_mt.c
Labels: sprint goal, no changelog

#6040 test: fix static variable for clang
  src/test/core_log_default_function/core_log_default_function.c
Labels: sprint goal, no changelog

#6044 test: don't configure the log function for PMEMOBJ nor PMEMCORE
  src/core/out.h
  src/test/Makefile.inc
  src/test/core_log/Makefile.inc
  src/test/core_log/TESTS.py
  src/test/core_log_default_function/Makefile
  src/test/core_log_default_function/TESTS.py
  src/test/core_log_function_mt/Makefile
  src/test/core_log_function_mt/TESTS.py
  src/test/core_log_internal/TESTS.py
  src/test/core_log_internal/core_log_internal.c
  src/test/core_log_max/TESTS.py
  src/test/core_log_no_func/TESTS.py
  src/test/core_log_no_func/core_log_no_func.c
  src/test/core_log_threshold_mt/Makefile
  src/test/core_log_threshold_mt/TESTS.py
  src/test/unittest/Makefile
  src/test/unittest/unittest.h
  src/test/unittest/ut_log.c
Labels: sprint goal, no changelog

#6045 common: various clang fixes
  .github/workflows/main.yml
  src/test/Makefile.inc
  src/test/core_log/core_log_common.c
  src/test/core_log/core_log_common.h
  src/test/core_log_function_mt/core_log_function_mt.c
  src/test/core_log_threshold_mt/core_log_threshold_mt.c
  src/test/unittest/README
  src/test/unittest/unittest.h
Labels: sprint goal, no changelog

#6046 common: update actions/checkout to v4
  .github/workflows/docker_rebuild.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/pmem.io_doc_update.yml
  .github/workflows/pmem_ras.yml
  .github/workflows/pmem_test_matrix.yml
  .github/workflows/pmem_tests.yml
  .github/workflows/scan_bandit.yml
  .github/workflows/scan_codeql.yml
  .github/workflows/scan_coverage.yml
  .github/workflows/scan_coverity.yml
  .github/workflows/scan_documentation.yml
  .github/workflows/scan_log_calls.yml
  .github/workflows/scan_stack_usage.yml
  .github/workflows/scan_ubsan.yml
  .github/workflows/ubuntu.yml
Labels: sprint goal, no changelog

#6051 common: remove unsupported FreeBSD related define
  src/core/valgrind_internal.h
Labels: obsolete-src, no changelog

#6047 test: UT for core_log_set_function()
  src/test/core_log/TESTS.py
  src/test/core_log/core_log.c
  src/test/core_log/core_log_common.c
  src/test/core_log/core_log_common.h
Labels: sprint goal, no changelog

#6054 common: add log.h to libpmemobj.h
  src/include/libpmemobj.h
Labels: sprint goal, no changelog

#6043 doc: logging function documentation
  doc/Makefile
  doc/libpmemobj/.gitignore
  doc/libpmemobj/pmemobj_log_get_threshold.3.md
  doc/libpmemobj/pmemobj_log_set_function.3.md
  doc/libpmemobj/pmemobj_log_set_threshold.3.md
  src/include/libpmemobj/log.h
Labels: sprint goal, no changelog

#5946 pmemobj: introduce fuses against ill-considered use of NDCTL_ENABLE=n
  .github/workflows/main.yml
  ChangeLog
  src/libpmemobj/Makefile
Labels: libpmemobj, sprint goal

#6056 doc: add an exception and a macro
  doc/Makefile
  doc/libpmemobj/pmemobj_log_use_default_function.3
  utils/check_docs/exceptions.txt
Labels: sprint goal, no changelog

#6058 common: allow check_license to apply proposed changes
  .github/workflows/main.yml
  utils/check_license/check-headers.sh
Labels: sprint goal, no changelog

#6059 pmem: add pmem_log_set_function function + UT
  src/include/libpmem.h
  src/libpmem/libpmem.c
  src/test/Makefile
  src/test/pmem_log_set_function/.gitignore
  src/test/pmem_log_set_function/Makefile
  src/test/pmem_log_set_function/TESTS.py
  src/test/pmem_log_set_function/pmem_log_set_function.c
Labels: sprint goal, no changelog

#5950 common: Clean-up Valgrind usage in the project
  .github/actions/pmem_test_prepare/action.yml
  .github/workflows/pmem_test_matrix.yml
  .github/workflows/pmem_tests.yml
  .github/workflows/scan_codeql.yml
  ChangeLog
  INSTALL.md
  src/benchmarks/Makefile
  src/core/valgrind_internal.h
  src/examples/Makefile.inc
  src/libpmem2/x86_64/memcpy/memcpy_avx.h
  src/libpmem2/x86_64/memcpy/memcpy_sse2.h
  src/libpmem2/x86_64/memset/memset_avx.h
  src/libpmem2/x86_64/memset/memset_sse2.h
  src/libpmemobj/heap.c
  src/libpmemobj/heap.h
  src/libpmemobj/obj.c
  src/libpmemobj/palloc.c
  src/libpmemobj/palloc.h
  src/test/Makefile
  src/test/RUNTESTS.py
  src/test/unittest/Makefile
  src/test/unittest/unittest.sh
  src/test/unittest/valgrind.py
  src/test/valgrind_check/.gitignore
  src/test/valgrind_check/Makefile
  src/test/valgrind_check/README
  src/test/valgrind_check/TEST0
  src/test/valgrind_check/valgrind_check.c
  utils/call_stacks_analysis/make_extra.py
  utils/gha-runners/build-pmdk.sh
Labels: Priority: 1 urgent, DAOS, sprint goal, no changelog

#6066 common: include new logging functions in linkers files
  src/libpmem/libpmem.link.in
  src/libpmemobj/libpmemobj.link.in
  src/test/scope/out2.log.match
  utils/call_stacks_analysis/make_extra.py
Labels: Priority: 1 urgent, sprint goal, no changelog

#6069 common: benchmarking utility and workflow
  .github/actions/pmem_benchmark_run/action.yml
  .github/workflows/pmem_benchmark.yml
  src/benchmarks/obj_pmalloc.cpp
  src/benchmarks/pmemobj_tx.cpp
  utils/ansible/opensuse-setup.yml
  utils/ansible/rockylinux-setup.yml
  utils/benchmarks/run_and_combine.py
Labels: sprint goal, no changelog

#6063 test: suppress ERROR messages when irrelevant to the test result
  src/test/obj_tx_locks/TEST1
  src/test/out_err_mt/TEST1
  src/test/out_err_mt/TEST2
  src/test/util_ctl/TEST0
  src/test/util_ctl/TEST1
Labels: sprint goal, no changelog
