Repository pmem/pmdk, pull requests merged in 2024-07, with the labels that each got.

#5941 common: remove non-Linux support from all build paths
  ChangeLog
  src/common.inc
  src/common/pmemcommon.inc
  src/libpmem/Makefile
  src/libpmem2/Makefile
  src/libpmem2/auto_flush_none.c
  src/libpmem2/deep_flush_other.c
  src/libpmem2/extent_none.c
  src/libpmem2/pmem2_utils_other.c
  src/test/Makefile.inc
  src/test/pmem2_persist/Makefile
  src/test/tools/extents/Makefile
  utils/call_stacks_analysis/make_cflow.sh
Labels: build system, obsolete-src

#6101 common: update files for updating repositories
  .github/workflows/pmem_ras.yml
  utils/gha-runners/run-ras-linux.yml
Labels: sprint goal, no changelog

#6103 common: improve the PMEM RAS workflow output
  .github/workflows/pmem_ras.yml
  utils/gha-runners/run-ras-linux.yml
Labels: sprint goal, no changelog

#6104 common: fix typo in pmem_tests.yml file
  .github/actions/pmem_test_prepare/action.yml
  .github/workflows/pmem_tests.yml
Labels: no changelog
