Repository pmem/pmdk, pull requests merged in 2024-02, with the labels that each got.

#5988 Core log warning
  src/common/file.c
  src/common/mmap.c
  src/common/os_deep_linux.c
  src/common/set.c
  src/common/shutdown_state.c
  src/common/uuid.c
  src/common/uuid_linux.c
  src/libpmem/pmem.c
  src/libpmemobj/heap.c
  src/libpmemobj/lane.c
  src/libpmemobj/list.c
  src/libpmemobj/memops.c
  src/libpmemobj/obj.c
  src/libpmemobj/palloc.c
  src/libpmempool/pool.c
  src/libpmempool/replica.c
  src/libpmempool/rm.c
  src/libpmempool/sync.c
  src/libpmempool/transform.c
  src/test/pmempool_sync/TEST10
  src/test/pmempool_sync/TEST11
  src/test/pmempool_sync/TEST23
  src/test/pmempool_sync/TEST24
  src/test/pmempool_sync/TEST29
  src/test/pmempool_sync/TEST32
  src/test/pmempool_sync/TEST33
  src/test/pmempool_sync/TEST34
  src/test/pmempool_sync/TEST35
  src/test/pmempool_sync/TEST36
  src/test/pmempool_sync/TEST37
  src/test/pmempool_sync/TEST42
  src/test/pmempool_sync/TEST43
  src/test/pmempool_sync/TEST44
  src/test/pmempool_sync/TEST45
  src/test/pmempool_sync/TEST46
  src/test/pmempool_sync/TEST47
  src/test/pmempool_sync/TEST48
  src/test/pmempool_sync/TEST49
  src/test/pmempool_sync/TEST50
  src/test/pmempool_sync/TEST51
  src/test/pmempool_sync/TEST52
  src/test/pmempool_sync/TEST53
  src/test/pmempool_sync/TEST8
  src/test/pmempool_sync/TEST9
  src/test/pmempool_transform/TEST5
  src/test/pmempool_transform/TEST6
  src/test/traces/traces.c
  src/test/util_poolset/grep0.log.match
  src/test/util_poolset/grep1.log.match
  src/test/util_poolset/grep2.log.match
  src/test/util_poolset/grep6.log.match
  src/tools/pmempool/common.c
Labels: sprint goal, no changelog

#5997 test: re-enable pmempool_transform[9,12]
  src/test/pmempool_transform/TEST12
  src/test/pmempool_transform/TEST9
Labels: sprint goal, no changelog

#5995 common: rename error_msg -> last_error_msg
  src/core/error_msg.h
  src/core/last_error_msg.c
  src/core/last_error_msg.h
  src/core/out.c
  src/core/pmemcore.h
  src/core/pmemcore.inc
  src/libpmem/Makefile
  src/libpmem/libpmem.c
  src/libpmem2/errormsg.c
  src/libpmem2/pmem2_utils.h
  src/libpmemobj/libpmemobj.c
  src/libpmempool/libpmempool.c
  src/test/Makefile.inc
  src/test/out_err/out_err.c
  src/tools/pmempool/rm.c
Labels: sprint goal, no changelog

#5994 common: do not call ERR_W(O)_ERRNO just to write to TLS
  src/common/os_deep_linux.c
  src/common/uuid_linux.c
  src/core/log.c
  src/core/log_default.c
  src/core/log_default.h
  src/core/log_internal.h
  src/core/out.c
  src/core/out.h
  src/libpmem2/auto_flush_linux.c
  src/libpmem2/deep_flush_linux.c
  src/libpmemobj/obj.c
  src/test/log_errno/TEST0
  src/test/log_errno/log_errno.c
  src/test/unittest/unittest.h
  src/test/unittest/ut_log.c
Labels: sprint goal, no changelog

#5998 test: re-enable obj_tx_add_range[3] and obj_tx_add_range_direct[2]
  src/test/obj_tx_add_range/TESTS.py
  src/test/obj_tx_add_range_direct/TESTS.py
Labels: sprint goal, no changelog

#5996 common: extract core_log aliases and core_asserts
  src/common/bad_blocks.c
  src/common/ctl.c
  src/common/mmap_posix.c
  src/common/pool_hdr.c
  src/common/set.h
  src/common/util_pmem.h
  src/common/uuid.c
  src/common/uuid_linux.c
  src/common/vec.h
  src/core/alloc.c
  src/core/core_assert.h
  src/core/last_error_msg.c
  src/core/log_internal.h
  src/core/out.h
  src/core/ravl.c
  src/core/sys_util.h
  src/core/util_posix.c
  src/libpmem/pmem_posix.c
  src/libpmem2/auto_flush_linux.c
  src/libpmem2/badblocks.c
  src/libpmem2/errormsg.c
  src/libpmem2/numa_none.c
  src/libpmem2/pmem2_arch.h
  src/libpmem2/pmem2_utils.h
  src/libpmem2/usc_none.c
  src/libpmem2/x86_64/init.c
  src/libpmem2/x86_64/memcpy/memcpy_avx.h
  src/libpmem2/x86_64/memcpy/memcpy_sse2.h
  src/libpmem2/x86_64/memset/memset_avx.h
  src/libpmem2/x86_64/memset/memset_sse2.h
  src/libpmemobj/alloc_class.c
  src/libpmemobj/lane.c
  src/libpmemobj/list.c
  src/libpmemobj/memblock.c
  src/libpmemobj/stats.c
  src/libpmemobj/tx.c
  src/libpmemobj/ulog.c
  src/test/tools/obj_verify/obj_verify.c
  src/test/unittest/unittest.h
  src/tools/pmempool/output.c
Labels: sprint goal, no changelog

#6001 common: fine-tuned _CORE_LOG_MAX_ERRNO_MSG
  src/core/log_internal.h
  src/test/Makefile
  src/test/core_log/.gitignore
  src/test/core_log/Makefile
  src/test/core_log/TESTS.py
  src/test/core_log/core_log.c
Labels: sprint goal, no changelog

#6000 common: pass all logs through legacy out if...
  src/core/out.c
  src/test/ex_libpmemobj/TEST0
  src/test/ex_libpmemobj/TEST1
  src/test/ex_libpmemobj/TEST17
  src/test/ex_libpmemobj/TEST7
  src/test/ex_libpmemobj/TEST8
  src/test/ex_libpmemobj/TEST9
  src/test/pmempool_sync/TEST10
  src/test/pmempool_sync/TEST11
  src/test/pmempool_sync/TEST12
  src/test/pmempool_sync/TEST23
  src/test/pmempool_sync/TEST24
  src/test/pmempool_sync/TEST25
  src/test/pmempool_sync/TEST26
  src/test/pmempool_sync/TEST29
  src/test/pmempool_sync/TEST32
  src/test/pmempool_sync/TEST33
  src/test/pmempool_sync/TEST34
  src/test/pmempool_sync/TEST35
  src/test/pmempool_sync/TEST36
  src/test/pmempool_sync/TEST37
  src/test/pmempool_sync/TEST42
  src/test/pmempool_sync/TEST43
  src/test/pmempool_sync/TEST44
  src/test/pmempool_sync/TEST45
  src/test/pmempool_sync/TEST46
  src/test/pmempool_sync/TEST47
  src/test/pmempool_sync/TEST48
  src/test/pmempool_sync/TEST49
  src/test/pmempool_sync/TEST50
  src/test/pmempool_sync/TEST51
  src/test/pmempool_sync/TEST52
  src/test/pmempool_sync/TEST53
  src/test/pmempool_sync/TEST8
  src/test/pmempool_sync/TEST9
  src/test/pmempool_transform/TEST10
  src/test/pmempool_transform/TEST12
  src/test/pmempool_transform/TEST3
  src/test/pmempool_transform/TEST5
  src/test/pmempool_transform/TEST6
  src/test/traces/TEST6
  src/test/traces/custom_file0.log.match
  src/test/traces/redir_stderr1.log.match
  src/test/traces/redir_stderr2.log.match
  src/test/traces/redir_stderr3.log.match
  src/test/traces/redir_stderr4.log.match
  src/test/traces/redir_stderr5.log.match
  src/test/traces/redir_stderr6.log.match
  src/test/traces/traces.c
Labels: sprint goal, no changelog

#6003 common: call abort() after reporting a fatal issue
  src/core/log_internal.h
Labels: sprint goal, no changelog

#6004 common: reenabling fully libpmempool_feature and pmempool_info tests
  src/test/libpmempool_feature/common.sh
  src/test/pmempool_info/TEST0
  src/test/pmempool_info/out0.log.match
  src/test/pmempool_info/out27.log.match
  src/test/unittest/unittest.sh
Labels: sprint goal, no changelog

#6006 common: remove obsolete out_err()
  CODING_STYLE.md
  src/core/out.c
  src/core/out.h
  src/test/out_err/out0.log.match
  src/test/out_err/out_err.c
  src/test/out_err/traces0.log.match
  utils/call_stacks_analysis/make_extra.py
Labels: sprint goal, no changelog

#6005 common: remove support for NO_LIBPTHREAD build option
  ChangeLog
  src/core/last_error_msg.c
  src/core/last_error_msg.h
Labels: sprint goal, obsolete-src

#6007 Call stack analysis w/ core_log_default_function()
  src/core/out.c
  src/core/out.h
  src/core/util.h
  src/libpmempool/feature.c
  src/test/helgrind-log.supp
  src/test/tools/anonymous_mmap/anonymous_mmap.c
  src/test/tools/obj_verify/obj_verify.c
  src/tools/pmempool/output.h
  utils/call_stacks_analysis/make_extra.py
  utils/call_stacks_analysis/white_list.json
Labels: sprint goal, no changelog

#6009 common: use sudo for ipmctl command
  utils/gha-runners/get-system-info.sh
Labels: no changelog

#6002 common: test all TLS log messages for length
  src/core/last_error_msg.h
  src/libpmemobj/pmalloc.c
  src/test/core_log/.gitignore
  src/test/core_log/Makefile
  src/test/core_log/TESTS.py
  src/test/core_log/call_all.c
  src/test/core_log/call_all.c.generated
  src/test/core_log/call_all.h
  src/test/core_log/core_log.c
  utils/call_stacks_analysis/log_call_all_generate.py
Labels: sprint goal, no changelog

#6011 common: add a scanner for the log calls test
  .github/workflows/scan_log_calls.yml
  .github/workflows/scans.yml
  src/test/core_log/call_all.c.generated
  utils/call_stacks_analysis/log_call_all_generate.py
Labels: sprint goal, no changelog

#6010 common: log w/ errno handled internally
  src/core/log.c
  src/core/log_internal.h
  src/test/core_log/core_log.c
  utils/call_stacks_analysis/README.md
Labels: sprint goal, no changelog

#6014 common: stop using subprocess with shell=True
  utils/call_stacks_analysis/log_call_all_generate.py
Labels: sprint goal, no changelog

#6016 Separate tests to verify max expected log message size
  src/core/log.c
  src/core/log_internal.h
  src/test/Makefile
  src/test/core_log/.gitignore
  src/test/core_log_max/.gitignore
  src/test/core_log_max/Makefile
  src/test/core_log_max/TESTS.py
  src/test/core_log_max/call_all.c
  src/test/core_log_max/call_all.c.generated
  src/test/core_log_max/call_all.h
  src/test/core_log_max/core_log_max.c
  utils/call_stacks_analysis/log_call_all_generate.py
Labels: sprint goal, no changelog

#6020 common: introduce logging level HARK
  src/core/log.c
  src/core/log_default.c
  src/core/log_internal.h
  src/core/out.c
  src/include/libpmemobj/log.h
  src/libpmempool/replica.c
  src/libpmempool/sync.c
  src/libpmempool/transform.c
  src/test/traces/custom_file0.log.match
  src/test/traces/redir_stderr2.log.match
  src/test/traces/redir_stderr3.log.match
  src/test/traces/redir_stderr4.log.match
  src/test/traces/redir_stderr5.log.match
  src/test/traces/traces.c
  src/test/unittest/ut_log.c
Labels: sprint goal, no changelog

#6021 common: print basic lib info when new logging function is set
  src/core/log.c
  src/core/out.c
  src/test/arch_flags/log0.log.match
  src/test/core_log_max/call_all.c.generated
  src/test/out_err/traces0.log.match
  src/test/traces/custom_file0.log.match
  src/test/traces/redir_stderr2.log.match
  src/test/traces/redir_stderr3.log.match
  src/test/traces/redir_stderr4.log.match
  src/test/traces/redir_stderr5.log.match
  src/test/util_poolset/grep0.log.match
  src/test/util_poolset/grep1.log.match
  src/test/util_poolset/grep10.log.match
  src/test/util_poolset/grep2.log.match
  src/test/util_poolset/grep3.log.match
  src/test/util_poolset/grep4.log.match
  src/test/util_poolset/grep5.log.match
  src/test/util_poolset/grep6.log.match
  src/test/util_poolset/grep7.log.match
Labels: sprint goal, no changelog

#6027 common: missing header file stdarg.h added
  src/libpmemobj/tx.c
  src/libpmempool/check_util.c
  src/libpmempool/feature.c
Labels: sprint goal, no changelog

#6023 common: start PMem tests at 6:00 pm to get results early next day
  .github/workflows/pmem_tests.yml
Labels: sprint goal, no changelog

#6025 common: run coverage scan in paralel w/ Ubuntu build
  .github/workflows/main.yml
Labels: sprint goal, no changelog

#6022 common: exclude line_no from call_all.c.generated
  .github/workflows/scan_log_calls.yml
  src/test/core_log_max/call_all.c.generated
  utils/call_stacks_analysis/log_call_all_generate.py
Labels: sprint goal, no changelog

#6030 common: remove core_log_to_last
  src/core/log.c
  src/core/log_internal.h
  src/test/core_log_max/core_log_max.c
Labels: sprint goal, no changelog

#6028 common: inrease total stack usage limit causes by new logging function
  .github/workflows/scan_stack_usage.yml
  utils/call_stacks_analysis/README.md
Labels: sprint goal, no changelog

#6032 test: fix util_poolset test to work w/o ndctl
  src/test/arch_flags/log0.log.match
  src/test/util_poolset/grep7.log.match
Labels: sprint goal, no changelog

#6026 common: no out_*() functions in release build
  src/core/out.c
  src/core/out.h
Labels: sprint goal, no changelog

#6031 test: CORE_LOG_* UT
  src/test/Makefile
  src/test/core_log_internal/.gitignore
  src/test/core_log_internal/Makefile
  src/test/core_log_internal/TESTS.py
  src/test/core_log_internal/core_log_internal.c
  src/test/unittest/unittest.h
Labels: sprint goal, no changelog
