Repository pmem/pmdk, pull requests merged in 2024-04, with the labels that each got.

#6067 obj: unify description with implementation pmemobj_log* fun
  src/include/libpmemobj/log.h
  src/libpmemobj/obj_log.c
Labels: sprint goal, no changelog

#6064 common: log uses unsigned instead of int for line_no as it is done in DAOS/vos
  doc/libpmemobj/pmemobj_log_set_function.3.md
  src/core/log.c
  src/core/log_default.c
  src/core/log_default.h
  src/core/log_internal.h
  src/core/out.c
  src/core/out.h
  src/include/libpmem.h
  src/include/libpmemobj/log.h
  src/test/core_log/core_log_common.c
  src/test/core_log/core_log_common.h
  src/test/core_log_default_function/core_log_default_function.c
  src/test/core_log_function_mt/core_log_function_mt.c
  src/test/core_log_internal/core_log_internal.c
  src/test/core_log_max/core_log_max.c
Labels: sprint goal, no changelog

#6065 common: avoid pmem_ prefix for pmem2 functions
  src/libpmem2/x86_64/init.c
  utils/call_stacks_analysis/make_call_stacks.py
  utils/call_stacks_analysis/make_extra.py
Labels: sprint goal, no changelog

#6071 common: 2.1.0 documentation update
  ChangeLog
Labels: sprint goal

#5943 common: fix support of OS_DIMM_CFLAG
  src/common.inc
Labels: sprint goal, obsolete-src, no changelog

#6072 benchmark: tune perf.cfg for longer execution times
  src/benchmarks/perf.cfg
Labels: sprint goal, no changelog

#6074 obj: verify the shutdown state in pmemobj pool
  src/common/set.c
Labels: sprint goal, no changelog

#6073 doc: add missing doc file
  doc/libpmem/pmem_log_use_default_function.3
Labels: sprint goal, no changelog

#6075 common: add SDS related CORE_LOG_WARNING to core_log_max test
  src/test/core_log_max/call_all.c.generated
  src/test/core_log_max/core_log_max.c
Labels: sprint goal, no changelog

#6076 doc: remove unneeded file
  doc/Makefile
  doc/libpmem/pmem_log_use_default_function.3
Labels: sprint goal, no changelog

#6078 utils: change lower_limit
  .github/workflows/scan_stack_usage.yml
  utils/call_stacks_analysis/README.md
Labels: sprint goal, no changelog
