Repository pmem/pmdk, pull requests merged in 2024-01, with the labels that each got.

#5961 common: remove obsolete custom print function
  src/core/out.c
  src/core/out.h
  src/test/Makefile
  src/test/traces_custom_function/.gitignore
  src/test/traces_custom_function/Makefile
  src/test/traces_custom_function/TEST0
  src/test/traces_custom_function/TEST1
  src/test/traces_custom_function/out0.log.match
  src/test/traces_custom_function/out1.log.match
  src/test/traces_custom_function/traces_custom_function.c
  src/test/traces_pmem/.gitignore
  src/test/traces_pmem/Makefile
  src/test/traces_pmem/TEST0
  src/test/traces_pmem/trace_pmem_head0.log.match
  src/test/traces_pmem/trace_pmemobj_head0.log.match
  src/test/traces_pmem/traces_pmem.c
  utils/call_stacks_analysis/make_extra.py
  utils/call_stacks_analysis/white_list.json
Labels: sprint goal, obsolete-src, no changelog

#5962 common: introduce LOG_ALWAYS for library info logging
  src/core/log.c
  src/core/log_default.c
  src/core/log_internal.h
  src/core/out.c
  src/core/out.h
  src/test/Makefile.inc
  src/test/drd-log.supp
  src/test/pmem2_persist_valgrind/Makefile
  src/test/pmem2_persist_valgrind/pmem2_persist_valgrind.c
  src/test/unittest/Makefile
  src/test/unittest/unittest.h
  src/test/unittest/ut_log.c
  src/test/util_ravl/Makefile
Labels: sprint goal, no changelog

#5964 common: use ut-dedicated logging function for pmemobj logs
  src/test/Makefile.inc
  src/test/helgrind-log.supp
  src/test/unittest/Makefile
  src/test/unittest/unittest.h
  src/test/util_ravl/Makefile
Labels: sprint goal, no changelog

#5970 common: upload test logs
  .github/workflows/ubuntu.yml
Labels: no changelog

#5975 common: skip checking changelog for master and stable-* branches xD
  .github/workflows/main.yml
Labels: no changelog

#5969 common: does not allow open pmem w/o USC
  ChangeLog
  src/common/ctl.c
  src/common/shutdown_state.c
  src/test/ctl_cow/TEST0
  src/test/ctl_cow/TEST3
  src/test/obj_ctl_arenas/TEST8
  src/test/obj_ctl_arenas/TEST9
  src/test/obj_defrag/TESTS.py
  src/test/obj_defrag_advanced/TESTS.py
  src/test/obj_extend/TEST1
  src/test/obj_pool_open_mt/TESTS.py
  src/test/obj_tx_user_data/TESTS.py
  src/test/pmem2_granularity_detection/TESTS.py
  src/test/pmempool_check/common.sh
  src/test/pmempool_feature/TEST14
  src/test/pmempool_feature/TEST15
  src/test/unittest/basetest.py
  src/test/unittest/unittest.sh
  utils/build-dpkg.sh
  utils/build-rpm.sh
  utils/docker/build-CI.sh
Labels: Priority: 1 urgent, libpmemobj, sprint goal

#5977 common: Removing the annoying test directory suffix
  src/test/unittest/unittest.sh
Labels: Priority: 1 urgent, sprint goal, no changelog

#5980 pmem: disable flag verification until #5979 is fixed
  src/libpmem/pmem.c
Labels: sprint goal, no changelog

#5976 err() with explicit errno
  src/core/out.c
  src/core/out.h
  src/core/util.h
  src/core/util_posix.c
  src/test/out_err/out_err.c
  src/tools/pmempool/output.c
  src/tools/pmempool/output.h
Labels: sprint goal, no changelog

#5967 Pmemobj error via ERR() instead of LOG(1,...
  src/libpmemobj/pmalloc.c
  src/libpmemobj/tx.c
  src/libpmemobj/ulog.c
Labels: sprint goal, no changelog

#5986 common: add out_log_va to white list
  utils/call_stacks_analysis/white_list.json
Labels: sprint goal, no changelog

#5973 common: fix coverity issue 1969782
  src/core/log.c
Labels: sprint goal, no changelog

#5978 common: final touch for the default logging function
  src/core/log_default.c
Labels: sprint goal, no changelog

#5985 common: introduce a separate FATAL macro with errno
  src/common/set.c
  src/common/util_pmem.h
  src/core/alloc.c
  src/core/log_default.c
  src/core/log_internal.h
  src/core/out.c
  src/core/out.h
  src/core/sys_util.h
  src/libpmem/pmem.c
  src/libpmem2/aarch64/init.c
  src/libpmem2/map_posix.c
  src/libpmem2/mcsafe_ops_posix.c
  src/libpmem2/pmem2_utils.c
  src/libpmem2/source_posix.c
  src/libpmem2/x86_64/init.c
  src/libpmemobj/alloc_class.c
  src/libpmemobj/heap.c
  src/libpmemobj/lane.c
  src/libpmemobj/list.c
  src/libpmemobj/memblock.c
  src/libpmemobj/memops.c
  src/libpmemobj/obj.c
  src/libpmemobj/palloc.c
  src/libpmemobj/pmalloc.c
  src/libpmemobj/stats.c
  src/libpmemobj/sync.h
  src/libpmemobj/tx.c
  src/libpmemobj/ulog.c
  src/libpmempool/check_pool_hdr.c
  src/libpmempool/check_sds.c
  src/libpmempool/check_util.c
  src/libpmempool/sync.c
  src/test/obj_ctl_arenas/obj_ctl_arenas.c
  src/test/pmem2_perror/pmem2_perror.c
  src/test/pmem_is_pmem_posix/pmem_is_pmem_posix.c
  utils/call_stacks_analysis/white_list.json
Labels: sprint goal, no changelog

#5987 Core log error
  src/common/bad_blocks.c
  src/common/ctl.c
  src/common/file_posix.c
  src/common/mmap.c
  src/common/os_deep_linux.c
  src/common/set.c
  src/common/set_badblocks.c
  src/core/log_internal.h
  src/core/util_posix.c
  src/libpmem/pmem_posix.c
  src/libpmem2/auto_flush_linux.c
  src/libpmem2/badblocks_ndctl.c
  src/libpmem2/deep_flush.c
  src/libpmem2/deep_flush_linux.c
  src/libpmem2/deep_flush_other.c
  src/libpmem2/map.c
  src/libpmem2/map_posix.c
  src/libpmem2/numa_ndctl.c
  src/libpmem2/persist.c
  src/libpmem2/pmem2_utils_ndctl.c
  src/libpmem2/region_namespace_ndctl.c
  src/libpmempool/pool.c
  src/libpmempool/replica.c
  src/libpmempool/sync.c
  src/libpmempool/transform.c
  src/test/pmempool_transform/TEST10
  src/test/pmempool_transform/TEST5
  src/test/pmempool_transform/TEST6
  src/test/pmempool_transform/out10.log.match
  src/test/traces/traces.c
  src/test/util_poolset/grep1.log.match
Labels: sprint goal, no changelog
