Repository pmem/pmdk, pull requests merged in 2024-10, with the labels that each got.

#6118 common: remove obsolete code
  src/test/Makefile.inc
  src/test/unittest/unittest.h
Labels: sprint goal, no changelog

#6055 common: ansible_user support in ansible scripts
  utils/ansible/README.md
  utils/ansible/configure-pmem.yml
  utils/ansible/configure-self-hosted-runner.yml
  utils/ansible/opensuse-setup.yml
  utils/ansible/rockylinux-setup.yml
  utils/ansible/update-os.yml
Labels: build system, sprint goal, no changelog

#6115 test: start_time to be defined before clean() and setup()
  src/test/unittest/basetest.py
Labels: sprint goal, no changelog

#6119 common: make _CORE_LOG_TO_LAST macro internal
  src/core/log.c
  src/core/log_internal.h
Labels: sprint goal, no changelog

#6120 common: print Linux release name during build in Docker
  src/test/unittest/basetest.py
  utils/docker/prepare-for-build.sh
Labels: sprint goal, no changelog

#6052 common: extend SKIPed tests description
  src/test/unittest/unittest.sh
Labels: sprint goal, obsolete-src, no changelog

#6068 common: add default pre-commit configuration
  .github/workflows/docker_rebuild.yml
  .github/workflows/pmem_ras.yml
  .github/workflows/pmem_test_matrix.yml
  .gitignore
  .pre-commit-config.yml
  src/.clang-format
  src/benchmarks/README
  src/core/pmemcore.inc
  src/examples/libpmem2/Makefile
  src/examples/libpmemobj/pminvaders/.gitignore
  src/examples/libpmemobj/slab_allocator/.gitignore
  src/examples/libpmemobj/string_store_tx_type/Makefile
  src/test/ex_libpmem/Makefile
  src/test/libpmempool_backup/config.sh
  src/test/obj_basic_integration/config.sh
  src/test/obj_check/Makefile
  src/test/obj_include/Makefile
  src/test/obj_list/Makefile
  src/test/obj_memcheck/Makefile
  src/test/obj_memcheck_register/Makefile
  src/test/obj_persist_count/Makefile
  src/test/obj_pmemcheck/Makefile
  src/test/obj_toid/.gitignore
  src/test/obj_tx_add_range/config.sh
  src/test/obj_tx_mt/config.sh
  src/test/pmempool_check/config.sh
  src/test/util_map_proc/maps_align_freebsd
  src/test/util_map_proc/maps_align_linux
  src/test/util_map_proc/maps_all_freebsd
  src/test/util_map_proc/maps_all_linux
  src/test/util_map_proc/maps_end_freebsd
  src/test/util_map_proc/maps_end_linux
  src/test/util_map_proc/maps_none_freebsd
  src/test/util_map_proc/maps_none_linux
  utils/ansible/opensuse-setup.yml
  utils/ansible/rockylinux-setup.yml
  utils/docker/0001-travis-fix-travisci_build_coverity_scan.sh.patch
Labels: sprint goal, no changelog

#6124 common: revert (c) to align with general Copyright template
  .pre-commit-config.yml
Labels: sprint goal, no changelog

#6125 common: fix proxy domain setup in self-hosted runner
  utils/ansible/configure-self-hosted-runner.yml
Labels: sprint goal, no changelog

#6128 common: Zomzog/changelog-checker executed only for PR
  .github/workflows/main.yml
Labels: sprint goal, no changelog
