Repository pmem/pmdk, pull requests merged in 2025-02, with the labels that each got.

#6138 common: change lower_limit
  .github/workflows/scan_stack_usage.yml
  utils/call_stacks_analysis/README.md
Labels: sprint goal, no changelog

#6139 common: check clang version
  src/core/util.h
Labels: sprint goal, no changelog

#6141 Include HPE in general license files
  LICENSE.txt
  LICENSE/BSD-3-Clause
Labels: no changelog

#6143 Release2.1.1
  INSTALL.md
Labels: sprint goal, no changelog

#6146 Release 2.1.1-rc2
  ChangeLog
Labels: sprint goal

#6148 Merge master to stable-2.1 (2.1.1-rc2)
  ChangeLog
Labels: sprint goal, no changelog

#6150 Release 2.1.1
  ChangeLog
Labels: sprint goal, no changelog

#6151 Release 2.1.1
  ChangeLog
Labels: sprint goal
